### ISSUE TITLE
Align button inline with the text

### ISSUE THREAD

**Issue by shubhamjsx** [shubham-kumar10/yummy-bites#12]
### The edit button has to be aligned with the Launch date as per below:
| Current: | Expected: |
| ------------- | ------------- |
| <img align="left" src="https://user-images.githubusercontent.com/18024497/96353567-e678cc00-10ea-11eb-8764-4a205fa0a223.png">  | <img align="left" src="https://user-images.githubusercontent.com/18024497/96353783-e1b51780-10ec-11eb-953c-d60e5894a98c.jpg">|

Component: item-info

**Comment by bhagatparwinder** [comment]
I can do it

**Comment by shubhamjsx** [comment]
> I can do it
Great assigning it to you.

**Comment by bhagatparwinder** [comment]
Done: https://github.com/shubham-kumar10/yummy-bites/pull/13

**Comment by shubhamjsx** [comment]
Thanks @bhagatparwinder
