### ISSUE TITLE
Add test cases - App component

### ISSUE THREAD

**Issue by shubhamjsx** [shubham-kumar10/yummy-bites#9]
Need to add test cases for all components

**Comment by AlexandreInsua** [comment]
I'd like to work on this issue. Could you assign it to me?

**Comment by shubhamjsx** [comment]
Sure. Which components would you like to work on?

**Comment by AlexandreInsua** [comment]
The one with the least coverage. After checking I confirm.

**Comment by AlexandreInsua** [comment]
Hi  @shubham-kumar10. After seeing the coverage, I go work in app component. I'll create a specific branch for me and I'll send PR.

**Comment by AlexandreInsua** [comment]
@shubham-kumar10 Done.

**Comment by shubhamjsx** [comment]
@AlexandreInsua Are you working on any components?

**Comment by AlexandreInsua** [comment]
@bhagatparwinder, Yes, I'm working on signup component. I hope upload the tests today.
